### ISSUE TITLE
Compatibility of cuda

### ISSUE THREAD

**Issue by yunseok624** [peasant98/SAM2-Docker#7]
Hi, I have a cuda version of 12.0. Can pull the image with me having such cuda version?

**Comment by peasant98** [comment]
Hi, sorry for the late reply!

If you `nvidia-smi` output allows for a max version of at least CUDA 12.1, it should work, since it is CUDA in Docker.

Example:

![image](https://github.com/user-attachments/assets/ba7f04d9-a0b8-4844-9e1c-7ca8e86e17d9)


If that is not the case, let me know, and I can create a Docker image with CUDA 12.0 that should work with SAM2.
